### ISSUE TITLE
Knowledge about scripts

### ISSUE THREAD

**Issue by sbellver** [pedroamador/pvebackup#3]
Hi Pedro.

If I run backup.sh as README shows, I have a /backups/local/daily/pvebackup_config_server3_miércoles.tar.gz with /etc and /root from my hostname (not vm)

If I run _backup_period.sh weekly snapshot I have a backup with my vm's.

Ist ok? 

If I only want to have a vm's backups I only need to run the last script, I think.

Then, I need a 3 crontabs entries (one for daily, weekly and monthly).

And from _backup_period.sh I see:
`else
  maxfiles=2
  snapshotname="daily_`date +%u`_pvebackup"`

Then, into daily folder I will have only 2 backups, not 6; its ok?

Thanks!

**Comment by pedroamador** [comment]
Hi!

I can't believe it: I have seen this issue today, 3 years after you opened it. I'm sorry for that @sbellver 

Maybe you aren't using this script nowdays, so I will close the ticket. If you need support please open another ticket, I will be attend it.

Sorry
